**Quiz 1.**

Type in your Student ID and full name in the box below.

### Type in your student ID and Name here
ID 6434461423
Name Phichaphop Raqsaboon

In [ ]:
# Must run this statement first
#!pip install --quiet mxnet

In [ ]:
from mxnet import nd
import mxnet as mx

###1. Create tensors: $x_1$, $x_2$, $x_3$, $x_4$, $x_5$, $x_6$ and three constants $m$, $n$, and $k$ from following instructions.

1.1. $m = 3$, $n = 5$, $k = 4$

$x_1=\left[7\right]$, $x_2 = \left[1 \dots m\right]$, $x_3=\left[ \begin{array}{ccc} 3 & -2 & 0\\ 2 & 1 &1\end{array}\right]$,

 $x_4 = $ matrix of 1's which dimension $(n-m) \times n $, $x_5= \left[ \begin{array}{ccccc} 3 & -1 & 1 & -2 & 0\end{array}\right]$,

 $x_6= $ matrix of 1's which dimension equal to  $x_3 $.

In [ ]:
m = 3
n = 5
k = 4

x1 = nd.array([7])
x2 = nd.arange(1, m+1, 1)
x3 = nd.array([[3, -2, 0],
               [2, 1, 1]])
x4 = nd.ones((n-m, n))
x5 = nd.array([3, -1, 1, -2, 0])
x6 = nd.ones(x3.shape)


1.2. From 1.1, find the expression that would generate the following results. You are not allowed to type any constant in your expression. You do not need to use the index for any expression.

In [ ]:
# 1.2.1. The expression to generate
#>> [[ 6. -4.  0.]
#    [ 4.  2.  2.]]
# is
x3+x3


In [ ]:
# 1.2.2. The expression to generate
#>> [[10.  5.  7.]
#    [ 9.  8.  8.]]
# is
x3+x1


In [ ]:
# 1.2.3. The expression to generate (Using .as_np_ndarray() to transform it to use with mx.np.matmul)
#>> array([[ 5.,  5.,  5.,  5.,  5.],
#          [-1., -1., -1., -1., -1.],
#          [ 1.,  1.,  1.,  1.,  1.]])
# is
mx.np.matmul(x3.T.as_np_ndarray(), x4.as_np_ndarray())

In [ ]:
# 1.2.4. The expression to generate
#>> array([[[[ 0.],
#            [ 0.],
#            [ 0.],
#            [ 0.],
#            [ 0.]]],
#         [[[ 3.],
#           [-1.],
#           [ 1.],
#           [-2.],
#           [ 0.]]],
#         [[[ 6.],
#           [-2.],
#           [ 2.],
#           [-4.],
#           [ 0.]]]])
# is
nd.stack(nd.zeros_like(x5), x5, x5+x5).reshape(m, k-m, n, k-m)

In [ ]:
# 1.2.5. The expression to generate
#>> [[  5.   2.]
#    [-10.  -1.]
#    [ -4.  -1.]]
# is
nd.array([[n, (n-m)], [((m-k)*nd.sum(x4).asscalar()), (m-k)], [((m-k)*k), (m-k)]])